//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TADE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExaminerDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExaminerDetail()
        {
            this.CandidateVerifications = new HashSet<CandidateVerification>();
        }
    
        public int ExaminerId { get; set; }
        public string UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> LastCandidateAllocation { get; set; }
        public Nullable<bool> CandidateAllocated { get; set; }
        public Nullable<int> NumberofCandidatesAllocated { get; set; }
        public Nullable<int> Grade { get; set; }
        public bool Status { get; set; }
        public Nullable<bool> Emergency { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateVerification> CandidateVerifications { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
