//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TADE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamResult
    {
        public int ResultId { get; set; }
        public int CandidateId { get; set; }
        public string Date { get; set; }
        public int ExamId { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> Grade { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Explanation { get; set; }
    
        public virtual ExamType ExamType { get; set; }
        public virtual CandidateDetail CandidateDetail { get; set; }
    }
}
